.PHONY: clean All

All:
	@echo "----------Building project:[ CTAOnCTP - Debug ]----------"
	@cd "CTAOnCTP" && "$(MAKE)" -f  "CTAOnCTP.mk"
clean:
	@echo "----------Cleaning project:[ CTAOnCTP - Debug ]----------"
	@cd "CTAOnCTP" && "$(MAKE)" -f  "CTAOnCTP.mk" clean
